### ISSUE TITLE
[GENERAL] Definir workflow

### ISSUE THREAD

**Issue by ghost** [training-projects/apollo#1]
**Tecnologias:**
- **NPM**, como gerenciador de dependências;
- **Browsersync**;
- **Gulp**, como task runner;
- **gulp-plumber**, para tratamento de erros;
- **gulp-sourcemaps**;
- **Jade**, como template engine;
- **Stylus**, como pré processador;
- **autoprefixer-stylus**;
- **gulp-uglify**, para minificação de JS;
- **Bootstrap Carousel**;
- **gulp-imagemin**, para optimização de imagens.

**Convenções:**
- **ITCSS**, como arquitetura;
- **RSCSS**, como convenção de escrita de código CSS.

**Comment by idlua** [comment]
teste
